### ISSUE TITLE
Unable to install build-tools (ARM64)

### ISSUE THREAD

**Issue by TheGreyRaven** [saschpe/docker-android-sdk#15]
Hi!

I'm currently using your Docker image in my CI/CD pipeline and I have ran into an issue.
When I try to install a specific version of build-tools like this:
`sdkmanager --install "build-tools;29.0.2"`

I get this output:
```
Warning: Dependant package with key emulator not found!
Warning: Unable to compute a complete list of dependencies.
```

Have you had this issue or do you know what might be the cause?

Might also be worth mentioning that I'm running the version behind latest: `saschpe/android-sdk:31-jdk11.0.13_8` due to the latest version is only for `linux/amd64` and not `arm64`!

**Comment by saschpe** [comment]
Did you test with the latest published tags? I just recently changed it to a multi-architecture image.

**Comment by TheGreyRaven** [comment]
Unfortunately I can't run the latest version, it gives me the following output due to the `linux/amd64`:
`standard_init_linux.go:228: exec user process caused: exec format error`

I'm using Oracles ARM server if that is of any help!
