### ISSUE TITLE
Emulator on arm64 

### ISSUE THREAD

**Issue by Vermid** [saschpe/docker-android-sdk#16]
Hi saschpe,

The following error occurs when I try to install the emulator via sdkmanager (sdkmanager "emulator" or sdkmanager --install emulator).
Warning: Failed to find package 'emulator'

Docker info -> 
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.124-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 9.718GiB
 Name: docker-desktop
 ID: AO47:M6FG:DOZT:TJXD:Y542:OQMM:DQHL:TCUA:2XBU:Y6FM:6L4K:HLD2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8

Image: 
android-sdk:33-jdk11.0.16_8.

MacBook Pro with Silicon chip, Version 12.5.1 Monterey.

I have already tried to download the emulator and configure it. (https://developer.android.com/studio/emulator_archive)
But this runs into -> emulator_linux/emulator: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory.

Any advice would be greatly appreciated, thanks!

**Comment by saschpe** [comment]
Running the emulator on Apple M1 didn't work for a long time because it lacked support. Meanwhile, a proper package is available and should just work (tm). So simply try again after an `sdkmanager --update` ;-)

Regardless, this used to be an issue with the Android SDK and not with this OCI image.
